/* ── argos-state.js ── Session state variables and DOM refs ── */
/* State */
var sessionId            = null;
var orientationCost      = 0;
var currentContextTokens = 0;
var pinnedTurns          = [];
var artefacts            = [];
var pendingImage         = null;
var pendingFile          = null;
var retirementShown      = false;
var retirementPending    = false;
var cachedWakeContent    = null;
var lastWakeTimestamp    = null;
var isWaking             = false;
var turnSequence         = 0;
var countdownInterval    = null;
var invokeController     = null;
/* DOM refs — assigned in argos-init.js */
var conv;
var thinking;
var inputEl;
var btnSend;
var btnNew;
var btnContinue;
var tokenFill;
var tokenLabel;
var sessionDisp;
var errorState;
var fileInput;
var imgPreview;
var previewImg;
var previewName;
var panelEl;
var panelToggle;
var panelBadge;
var pannedSection;
var pinnedList;
var artefactsSection;
var artefactsList;
var panelEmpty;
var btnStop;
